// <auto-generated />
namespace RememberMeBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _26011528 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26011528));
        
        string IMigrationMetadata.Id
        {
            get { return "201701261428576_26-01-15-28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
